language: java
jdk:
  - openjdk10

before_install:
  - openssl aes-256-cbc -K $encrypted_f6daff8a5b58_key -iv $encrypted_f6daff8a5b58_iv
    -in cd/gpg.asc.enc -out cd/gpg.asc -d

install: "/bin/true"
script:
  - make build
deploy:
  - provider: script
    skip_cleanup: true
    script: make deploy-snapshot
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script: make deploy
    on:
      tags: true
